name: Run Pester Tests and Publish to PowerShell Gallery

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Pester
      shell: pwsh
      run: Import-Module -Name Pester -Version 4.10.1 -Force
    - name: Run Pester tests
      shell: pwsh
      run: Invoke-Pester -OutputFormat NUnitXml -OutputFile test-results.xml
    - name: Publish to PowerShell Gallery
      if: success()
      shell: pwsh
      run: Publish-Module -Name 'TestPubGQL' -NuGetApiKey '${{ secrets.PSGALLERY_TOKEN }}'
