name: Run Pester Tests and Publish to PowerShell Gallery

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Pester
      shell: pwsh
      run: Install-Module -Name Pester -RequiredVersion 4.10.1 -Force
    - name: Run Pester tests
      shell: pwsh
      run: Invoke-Pester
    - name: Publish to PowerShell Gallery
      if: success()
      shell: pwsh
      run: Publish-Module -Name 'PSGraphQL' -NuGetApiKey '${{ secrets.PSGALLERY_TOKEN }}' -WhatIf
