
name: Run Pester Test Validation
on:  
  push:
  pull_request:
    branches:
      - master

jobs:
  TestModule:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Pester
      shell: pwsh
      run: Install-Module -Name Pester -RequiredVersion 4.10.1 -Force
    - name: Run Pester Tests
      shell: pwsh
      run: Invoke-Pester
